const Labels = {
  title: "CAN YOU GUESS THE CARD?",
  startState: "startState",
  guessColorState: "guessColorState",
  guessColorPrompt: "Is the next card Black or Red?",
  guessHigherOrLowerState: "guessHigherOrLowerState",
  guessHigherOrLowerPrompt: "WIll the next card be higher or lower than the last one?",
  guessSuitState: "guessSuitState",
  guessSuitPrompt: "What suit do you think the next card belongs to?",
  spades: "S",
  clubs: "C",
  hearts: "H",
  diamonds: "D",
  black: "Black",
  red: "Red",
  restart: "Restart",
  continue: "Continue",
  correctGuess: "Correct! Nice Guess! Think You Can Do It Again?",
  incorrectGuess: "Oops! That's Incorrect :( Better Luck Next Time!",
  higher: "Higher",
  lower: "Lower",
  equal: "Equal",
  allCorrectGuesses: "Congratulations! All Your Guesses Were Correct!",
  someCorrectGuesses: "Nice Try! You Guessed A Few Correctly, Better Luck Next Time!",
  allInCorrectGuess: "Unfortunately, None Of Your Guesses Were Correct...",
};

export default Labels;
